<a href="https://colab.research.google.com/gist/shiqisc925-hub/68715723c315a8909ac87e4888bb70b8/-colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install --upgrade setuptools
!pip install --upgrade pip
!pip install nashpy
!pip install quantecon

import numpy as np
import nashpy as nash
import quantecon.game_theory as gt

endowment = 150
multiplier = 1.5
players = 2

contributions = [0, 50, 100, 150]
n_strategies = len(contributions)

payoff_matrix = np.zeros((n_strategies, n_strategies, 2))

for i, c0 in enumerate(contributions):
    for j, c1 in enumerate(contributions):
        public_pool = (c0 + c1) * multiplier
        share = public_pool / players
        payoff_matrix[i, j, 0] = endowment - c0 + share
        payoff_matrix[i, j, 1] = endowment - c1 + share

A = payoff_matrix[:,:,0]
B = payoff_matrix[:,:,1]

game = nash.Game(A, B)
print("=== NashPy: Normal Form Game Matrix ===")
print(game)

print("\n=== NashPy: Nash Equilibria (Support Enumeration) ===")
equilibria = game.support_enumeration()
for eq in equilibria:
    print(eq)

g_pg = gt.NormalFormGame(payoff_matrix)
print("\n=== QuantEcon: Normal Form Game Matrix ===")
print(g_pg)

NE_pure = gt.pure_nash_brute(g_pg)
print("\n=== QuantEcon: Pure Strategy Nash Equilibria ===")
print(NE_pure)

NE_mixed = gt.support_enumeration(g_pg)
print("\n=== QuantEcon: Mixed Strategy Nash Equilibria ===")
print(NE_mixed)


=== NashPy: Normal Form Game Matrix ===
Bi matrix game with payoff matrices:

Row player:
[[150.  187.5 225.  262.5]
 [137.5 175.  212.5 250. ]
 [125.  162.5 200.  237.5]
 [112.5 150.  187.5 225. ]]

Column player:
[[150.  137.5 125.  112.5]
 [187.5 175.  162.5 150. ]
 [225.  212.5 200.  187.5]
 [262.5 250.  237.5 225. ]]

=== NashPy: Nash Equilibria (Support Enumeration) ===
(array([1., 0., 0., 0.]), array([1., 0., 0., 0.]))

=== QuantEcon: Normal Form Game Matrix ===
2-player NormalFormGame with payoff profile array:
[[[150. , 150. ],  [187.5, 137.5],  [225. , 125. ],  [262.5, 112.5]],
 [[137.5, 187.5],  [175. , 175. ],  [212.5, 162.5],  [250. , 150. ]],
 [[125. , 225. ],  [162.5, 212.5],  [200. , 200. ],  [237.5, 187.5]],
 [[112.5, 262.5],  [150. , 250. ],  [187.5, 237.5],  [225. , 225. ]]]

=== QuantEcon: Pure Strategy Nash Equilibria ===
[(0, 0)]

=== QuantEcon: Mixed Strategy Nash Equilibria ===
[(array([1., 0., 0., 0.]), array([1., 0., 0., 0.]))]
